VER=1.1
NAME=jdcloud-wui-slim
DOC=$(NAME).html
OUT=lib/$(NAME).js
OUT_MIN=lib/$(NAME).min.js
CMT="$(NAME) version $(VER)"

all: $(OUT) $(OUT_MIN)

clean:
	-rm -rf $(OUT) $(OUT_MIN)

js: $(OUT)

$(OUT): example/jdcloud-wui-slim.html src/*
	P_CMT="$(NAME) version $(VER)" perl tool/webcc_merge.pl $< > $(OUT)

$(OUT_MIN): $(OUT)
	sh -c 'tool/jsmin $(CMT) < $< > $@'

split:
	@perl tool/webcc_split.pl $(OUT) src
